-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "ProjectType" ADD VALUE 'SOLAR_POWER';
ALTER TYPE "ProjectType" ADD VALUE 'WIND_POWER';
ALTER TYPE "ProjectType" ADD VALUE 'HYDRO_POWER';
ALTER TYPE "ProjectType" ADD VALUE 'BIOMASS_POWER';
ALTER TYPE "ProjectType" ADD VALUE 'GEOTHERMAL';
ALTER TYPE "ProjectType" ADD VALUE 'WASTE_TO_ENERGY';
ALTER TYPE "ProjectType" ADD VALUE 'EFFICIENT_LIGHTING';
ALTER TYPE "ProjectType" ADD VALUE 'EFFICIENT_APPLIANCES';
ALTER TYPE "ProjectType" ADD VALUE 'INDUSTRIAL_HEAT_RECOVERY';
ALTER TYPE "ProjectType" ADD VALUE 'EFFICIENT_MOTORS';
ALTER TYPE "ProjectType" ADD VALUE 'BIOMASS_COOKSTOVES';
ALTER TYPE "ProjectType" ADD VALUE 'LPG_ADOPTION';
ALTER TYPE "ProjectType" ADD VALUE 'COMMUNITY_KITCHENS';
ALTER TYPE "ProjectType" ADD VALUE 'LANDFILL_METHANE_CAPTURE';
ALTER TYPE "ProjectType" ADD VALUE 'COMPOSTING';
ALTER TYPE "ProjectType" ADD VALUE 'ANAEROBIC_DIGESTION';
ALTER TYPE "ProjectType" ADD VALUE 'WASTEWATER_METHANE';
ALTER TYPE "ProjectType" ADD VALUE 'AVOIDED_DEFORESTATION';
ALTER TYPE "ProjectType" ADD VALUE 'FORESTRY_MANAGEMENT';
ALTER TYPE "ProjectType" ADD VALUE 'MANGROVE_RESTORATION';
ALTER TYPE "ProjectType" ADD VALUE 'SOIL_CARBON_SEQUESTRATION';
ALTER TYPE "ProjectType" ADD VALUE 'BIOCHAR_PRODUCTION';
ALTER TYPE "ProjectType" ADD VALUE 'CEMENT_CCS';
ALTER TYPE "ProjectType" ADD VALUE 'POWER_PLANT_CCS';
ALTER TYPE "ProjectType" ADD VALUE 'MANGROVES_RESTORATION';
ALTER TYPE "ProjectType" ADD VALUE 'SEAGRASS_RESTORATION';
ALTER TYPE "ProjectType" ADD VALUE 'SALT_MARSH_PROJECTS';
ALTER TYPE "ProjectType" ADD VALUE 'DAIRY_MANURE_MANAGEMENT';
ALTER TYPE "ProjectType" ADD VALUE 'CATTLE_ENTERIC_FERMENTATION';
ALTER TYPE "ProjectType" ADD VALUE 'NO_TILL_FARMING';
ALTER TYPE "ProjectType" ADD VALUE 'COVER_CROPPING';
ALTER TYPE "ProjectType" ADD VALUE 'SOIL_ENRICHMENT';
ALTER TYPE "ProjectType" ADD VALUE 'COAL_TO_GAS';
ALTER TYPE "ProjectType" ADD VALUE 'DIESEL_TO_ELECTRIC';
